### ISSUE TITLE
图片过多导致图片详情页OOM

### ISSUE THREAD

**Issue by Karl9452** [Vanish136/ImagePicker#12]
之前测试发生的一个问题，如果我一个文件夹的图片很多（500左右大约），点击图片后，会将整个列表图片全部传入图片详情页，最终导致OOM。个人觉得要是点击图片只看当前一张就可以了，谢谢作者!

**Comment by Vanish136** [comment]
@Karl9452 这个问题已经修复过了，你试试最新版的

**Comment by Karl9452** [comment]
好的，多谢哦，好久没更新版本了，落后了哈哈
