### ISSUE TITLE
调用剪切doCrop模糊

### ISSUE THREAD

**Issue by Karl9452** [Vanish136/ImagePicker#15]
你好，我在使用图片选择库时如果调用了doCrop方法得到的图片很模糊，不是拉伸那种，是文件夹中图片就比较模糊，请问怎么解决呢

**Comment by Vanish136** [comment]
@Karl9452 你是指的原图就很模糊吗？如果是图片文本本身分辨率不高，那显示出来必然是模糊的，裁剪得到的图片分辨率也就不高。

**Comment by Karl9452** [comment]
不是的，我是说我去裁剪后得到的图片的文件夹去看，很模糊，并不是让他拉伸。我在源代码中找到了bitmap.compress中quality传的也是100，比较困惑这个问题

**Comment by Vanish136** [comment]
@Karl9452 是所有图片裁剪后都这样还是某一张图片呢？方便的话可以直接加我QQ505515031，讨论下

**Comment by Karl9452** [comment]
好的，多谢了!
