### ISSUE TITLE
裁剪图片时候报错

### ISSUE THREAD

**Issue by KongJue** [Vanish136/ImagePicker#16]
**java.lang.NoSuchMethodError**
> No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder')

**1**  com.lwkandroid.imagepicker.utils.GlideImagePickerDisplayer.display(GlideImagePickerDisplayer.java:38)

**2** com.lwkandroid.imagepicker.ui.grid.adapter.ImageContentItemView.setData(ImageContentItemView.java:55)

**3** com.lwkandroid.imagepicker.ui.grid.adapter.ImageContentItemView.setData(ImageContentItemView.java:21)

**4** com.lwkandroid.imagepicker.base.adapter.ImagePickerItemViewManager.setData(ImagePickerItemViewManager.java:86)

**5** com.lwkandroid.imagepicker.base.adapter.ImagePickerBaseAdapter.setData(ImagePickerBaseAdapter.java:119)

**6** com.lwkandroid.imagepicker.base.adapter.ImagePickerBaseAdapter.getView(ImagePickerBaseAdapter.java:103)

**Comment by Vanish136** [comment]
@KongJue 似乎是ImagePicker的内置Glide版本所依赖的support版本与项目中指定的版本不一致的原因，1.4.2版本已升级内置glide到4.7.1版本，对应的support版本为27.1.1，你引用为1.4.2版本就行了

**Comment by KongJue** [comment]
嗯，确实是依赖glide版本的与你不一致，导致出错，升级为1.4.2已解决此问题，谢谢。 @Vanish136
