### ISSUE TITLE
无法发起拍照请求

### ISSUE THREAD

**Issue by KongJue** [Vanish136/ImagePicker#17]
HUAWEI PRA-AL00X 华为荣耀8青春版 API 26 Android 8.0.0 
点击拍照时，此手机无法发起拍照请求

ImagePicker版本ver1.4.2

**Comment by Vanish136** [comment]
我用云真机测试了下，这两个机型没有问题啊，你确认是否给了拍照权限？能否顺便把错误日志发出来

**Comment by KongJue** [comment]
给了权限的，但是点击拍照按钮，Toast就显示此手机无法发起拍照请求，LogCat中也没有对应ImagePicker的Error日志，只有这款手机才有这个问题

**Comment by Vanish136** [comment]
你找一下warning日志，拍照的地方有try catch，不会直接崩溃

**Comment by KongJue** [comment]
java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/0000-0000/Android/data/.../cache/IMG_1532584778907.jpg
07-26 13:59:38.917 17935-17935/com.langsi.meicool W/System.err:     at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:738)
07-26 13:59:38.917 17935-17935/com.langsi.meicool W/System.err:     at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:417)
07-26 13:59:38.917 17935-17935/com.langsi.meicool W/System.err:     at com.lwkandroid.imagepicker.utils.TakePhotoCompatUtils.takePhoto(TakePhotoCompatUtils.java:78)
07-26 13:59:38.917 17935-17935/com.langsi.meicool W/System.err:     at com.lwkandroid.imagepicker.ui.grid.view.ImageDataActivity.doTakePhoto(ImageDataActivity.java:177)
07-26 13:59:38.917 17935-17935/com.langsi.meicool W/System.err:     at com.lwkandroid.imagepicker.ui.grid.view.ImageDataActivity.startTakePhoto(ImageDataActivity.java:171)
07-26 13:59:38.917 17935-17935/com.langsi.meicool W/System.err:     at com.lwkandroid.imagepicker.ui.grid.adapter.ImageCameraItemView$1.onClick(ImageCameraItemView.java:47)
07-26 13:59:38.917 17935-17935/com.langsi.meicool W/System.err:     at android.view.View.performClick(View.java:6291)
07-26 13:59:38.917 17935-17935/com.langsi.meicool W/System.err:     at android.view.View$PerformClick.run(View.java:24931)
07-26 13:59:38.917 17935-17935/com.langsi.meicool W/System.err:     at android.os.Handler.handleCallback(Handler.java:808)
07-26 13:59:38.918 17935-17935/com.langsi.meicool W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:101)
07-26 13:59:38.918 17935-17935/com.langsi.meicool W/System.err:     at android.os.Looper.loop(Looper.java:166)
07-26 13:59:38.918 17935-17935/com.langsi.meicool W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7425)
07-26 13:59:38.918 17935-17935/com.langsi.meicool W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-26 13:59:38.918 17935-17935/com.langsi.meicool W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
07-26 13:59:38.918 17935-17935/com.langsi.meicool W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by Vanish136** [comment]
@KongJue  方便加一下我QQ吗 505515031 一起讨论下

**Comment by Vanish136** [comment]
在这里写给所有遇到相同问题的人看看：
目前由于个人力量较小，无法适配到所有rom，部分国内厂商修改ROM后可能导致无法获取到sd卡真实路径，例如设置的缓存是`getExternalCacheDir().getAbsolutePath()`，但实际缓存位置并不在这个路径下，所以就会导致上面的错误，所以可将缓存路径设置为内部存储地址即可：
`getFilesDir().getAbsolutePath()`
