### ISSUE TITLE
编译不过啊

### ISSUE THREAD

**Issue by gooddaddy** [Vanish136/ImagePicker#19]
Android resource linking failed
Output:  /Users/bobo/Documents/worker/app/CashRegister/app/build/intermediates/incremental/mergeDevelopDebugResources/merged.dir/values/values.xml:589: error: resource android:attr/fontVariationSettings not found.
/Users/bobo/Documents/worker/app/CashRegister/app/build/intermediates/incremental/mergeDevelopDebugResources/merged.dir/values/values.xml:589: error: resource android:attr/ttcIndex not found.
error: failed linking references.

最新版本1.4.3 编译不过，1.4.2 可以编译过

**Comment by Vanish136** [comment]
@gooddaddy 1.4.3版本需要你的项目本身适配AndroidX，不然会有冲突
