### ISSUE TITLE
Glide更新到版本3.8.0吧

### ISSUE THREAD

**Issue by hegelsu** [Vanish136/ImagePicker#2]
Glide能否更新到版本3.8.0？

**Comment by Vanish136** [comment]
@hegelsu  目前版本是4.0.0-RC1，比3.X版本更高，架构更合理，不想使用这个版本的话可以参考README，exclude掉glide，然后自己写个工具类实现接口IImagePickerDisplayer，调用的时候传进去就行了

**Comment by hegelsu** [comment]
好的
