### ISSUE TITLE
兼容v4.fragment

### ISSUE THREAD

**Issue by hegelsu** [Vanish136/ImagePicker#4]
1. public void start(Fragment fragment, int requestCode)
目前没有处理v4.fragment
2. 目前用的是Xamarin的绑定进行使用的本库，但在绑定时会出现如下提示：不知道博主是否有什么办法消除这个提示：
missing class error was raised while reflecting com.lwkandroid.imagepicker.ui.pager.view.ImagePagerActivity$2 : Expecting a stackmap frame at branch target 52	ImagePicker-Lib	E:\GIT\ImagePicker.Droid\ImagePicker-Lib\JARTOXML		
以上错误换成1.7的sdk编译就没有问题了，不过我使用别人的lib也没有这样的现像，不知道是不是哪里要设置一下。

**Comment by Vanish136** [comment]
@hegelsu 
1. 下个版本加上去
2. 我没用过Xamarin,只能搜索了下报错的问题，目前来看配置Jdk到1.7可以消除这个警告。以下是我搜索到的答案，您也可以尝试看看有没有其他解决方案。
①https://stackoverflow.com/questions/40384950/xamarin-android-jartoxml-missing-class-error-was-raised-while-reflecting-classn
②https://stackoverflow.com/questions/26733946/java-lang-verifyerror-expecting-a-stackmap-frame-at-branch-target

**Comment by hegelsu** [comment]
1. v4.fragment的我只是在写Demo的时候遇到，暂时还不急，后面支持就可以了
2. 根据你的搜索结果解决了：
“This issue was cleared up in class-parse recently”
这真是坑，我看工程属性就是class-parse，结果要先选中jar2xml，再选一下class-parse才算真正用的class-parse这个选项，无语了。

谢谢，目前集成了博主两个库。
