### ISSUE TITLE
你好，我想您这个sdk,可不可以搞个国际化，有英文的了

### ISSUE THREAD

**Issue by androidget** [Vanish136/ImagePicker#6]
我的只是建议，看您有没有时间了，不然就完美了

**Comment by Vanish136** [comment]
@androidget 好的，我抽个时间更新下

**Comment by Vanish136** [comment]
@androidget 你看看V1.3.5

**Comment by hegelsu** [comment]
版本1.3.6拉不下来

**Comment by hegelsu** [comment]
不好意思，弄错了，看你的账号看成了1.3.6

**Comment by hegelsu** [comment]
升级了一下，安装apk时发现我的app名字变成ImagePicker了。。。

**Comment by Vanish136** [comment]
@androidget 
是这样的，1.3.5版本中，国际化的吹是把中文的文案单独提取到values-zh的文件夹下，默认的values中改为英文文案，那么你手机里默认语言是中文的，此时App会优先查找values-zh文件夹下的资源，不巧的是在values-zh中的文件夹里定义了我也定义了一个字段叫app_name=ImagePicker，所以App会显示这个名字。
解决方案也很简单，有两种：
①你在自己主Module中也新建一个values-zh的文件夹，添加一个strings.xml，在里面定义一个字段：app_name=你app的名字
②在主Moudule的AndroidManifest.xml中将android:label="@string/app_name"这里的名字换掉

**Comment by Vanish136** [comment]
@androidget 我待会儿再发个版本彻底改掉这个问题吧，确实是我的锅

**Comment by Vanish136** [comment]
@androidget @hegelsu 
V1.3.6版本应该没问题了

**Comment by hegelsu** [comment]
有没有考虑这样的情况，我的app本来就只有中文，那么无论在系统是中文还是英文的情况下，我的app都是中文，此时我是不希望在系统是英文情况下因为选择图片的库支持英文就变英文了的，也就是说主app希望无论什么情况都要是中文

**Comment by Vanish136** [comment]
@hegelsu 
这种情况就属于不需要国际化处理了，正常国际化处理就是跟随系统改变而改变的。
如果你真有这种需求，可以尝试下面的解决方案：
①自定义一个Application类，在onCreate()中指定本地语言：
public class AppApplication extends Application
{
    @Override
    public void onCreate()
    {
        super.onCreate();
        Resources resources = getResources();
        Configuration config = resources.getConfiguration();
        if (Build.VERSION.SDK_INT < 17)
            config.locale = Locale.CHINA;
        else
            config.setLocale(Locale.CHINA);
        resources.updateConfiguration(config, resources.getDisplayMetrics());
    }
}
②在AndroidManifest.xml中设置这个Application为入口即可

**Comment by hegelsu** [comment]
我觉得在最简洁集成的情况下应该在什么情况下都是中文，只有在需要多语言的时候才通过额外设置来支持多语言化，毕竟国内的纯只支持中文的还在绝大多数，毕竟现在做一个应用都是集成不少库，也不是每个误国都支持多语言

**Comment by Vanish136** [comment]
@hegelsu 
这个其实我觉得得看APP的市场定位了，如果就只打算在国内市场用，那确实只需要中文就行了，但是做开源项目不同，支持国际化处理是有一定必要的。
