### ISSUE TITLE
超过两千张 500k以上图片  点击图片预览崩溃

### ISSUE THREAD

**Issue by shenshihao520** [Vanish136/ImagePicker#8]

**Comment by shenshihao520** [comment]
出现android.os.TransactionTooLargeException: data parcel size 642356 bytes

**Comment by Vanish136** [comment]
@shenshihao520 
这个异常代表Intent中传递的数据太大。
而跳转到预览界面通过Intent传递的数据和图片本身大小无关，如下：
①当前查看图片的位置（预览界面和大图界面是复用的，这个参数是给大图界面用的）
②是否为预览模式
③所有图片的数据（某一文件夹下所有图片/所有已选中的图片数据，实体类ImageBean的集合）
④ImagePicker配置参数
从上面来看，数据量可能最大的就是③了，而我实际测试传递2000张图片也没有出现这个异常，所以不知道你的操作顺序是什么样的？能不能更详细的描述下？

**Comment by shenshihao520** [comment]
是在显示所有图片时 随便点击一张图片 就会报这个错误， 而且一定是2000张 500k以上的图片 。你试试  2000张低于500k的都复现不了，我看了一下你的预览跳转，Intent传了一个很大的数据，貌似是图片？  可以换成传地址试试

**Comment by Vanish136** [comment]
@shenshihao520 
嗯，我明白你说的意思，Intent中传递的图片数据没有Bitmap之类的数据，都是id、地址、所属文件夹之类的数据，照理来讲不会很大，当然不排除即使只有这些数据但是由于量级大了也会导致出现这个异常，我去找找大图片试试吧，下个版本把这里传递的机制改一下。

**Comment by Vanish136** [comment]
@shenshihao520 
1.3.7版本试试？
