### ISSUE TITLE
报空指针错误

### ISSUE THREAD

**Issue by lihuanming** [Vanish136/ImagePicker#9]
# pool-9-thread-1(437)
java.lang.NullPointerException
Attempt to invoke interface method 'void com.lwkandroid.imagepicker.ui.grid.view.IImageDataView.hideLoading()' on a null object reference

**Comment by Vanish136** [comment]
@lihuanming 我猜测是图片未扫描完之前就按了返回键导致的，针对这个可能我更新了一个版本，你试试v1.3.8

**Comment by lihuanming** [comment]
好的
